### ISSUE TITLE
Add a "phone type" element (landline vs mobile)

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-types-phonenumber#1]
@janinamincer-daszkiewicz proposed to add an element which would allow server developers to include information if a particular number is a landline number or a mobile one.

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members - Do you store this information in your databases (a phone number type)? Would you like other partners to share it with you? Do you have any thoughts on this?

**Comment by wrygiel** [comment]
My personal opinion is:
- **It's somewhat redundant**. There are libraries which can parse the number and provide this kind of information for the clients who need it. You can see a demo [here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) - `getNumberType()` detects Fixed-line, Mobile, Toll-free, Premium Rate, Shared Cost, VoIP and Personal Numbers (according to the specs).
- **It's probably not really trustworthy**. If I needed this information, and **if I could** use the library, then I would rather trust the output from the library.

**Comment by georgschermann** [comment]
we don't store or need this information
